#     ____                     _ ____        __
#    /  _/___ __  ______ ___  (_) __ )____  / /_
#    / //_  // / / / __ `__ \/ / __  / __ \/ __/
#  _/ /  / // /_/ / / / / / / / /_/ / /_/ / /_
# /___/ /___|__,_/_/ /_/ /_/_/_____/\____/\__/
#
# The multiple function QQ bot based on NoneBot.

general: #General configuration
  version: 3.0.0a0
  debug: false
  log:
    level: INFO
    format: >
      <level>
      <v>{level:<8}</v>
      [{time:YYYY/MM/DD} {time:HH:mm:ss.SSS} <d>{module}:{name}</d>]</level>
      {message}

server:
  listen: 127.0.0.1
  port: 8080
  driver: nonebot.drivers.fastapi

upstream:
  api_root: {}
  api_timeout: 30
  access_token: null
  secret: null

database: #Current only support PostgreSQL
  connection:
    host: localhost
    port: 5432
    password: ""
    user: postgres
    database: postgres
  pool:
    max: 16
    min: 1
  echo: false
  retry:
    limit: 1
    interval: 1

bot:
  superusers: []
  nickname: [""]
  command_start: ["!", "*", "/", "！", "＊", "／"]
  command_sep: ["."]
  session_expire_timeout: 120
