# 身份证生成返回消息格式
format: |
    {id_number}
    姓名:{name}
    性别:{gender}
    地址:{address}

    此数据根据国家公开的标准进行生成，不是真实存在的身份信息，仅供交流学习使用。

birth:
    begin: [1960, 01, 01] # 身份证出生日期起始点
    end: [2000, 12, 31] # 身份证出生日期结束点
