api:
    hitokoto: "https://v1.hitokoto.cn/" # 请求一言接口的API
    image: "https://cn.bing.com/HPImageArchive.aspx" # 请求bing接口的API
    thread: 8 # 同时下载图片的线程数

custom:
    time:
        hours: 8 # 目前没用
    format: |
        今天是{date}
        {image}
        {hitokoto}-{hitokoto_from}
        ======
        Image by bing
