# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Check

on:
    - push
    - pull_request

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Lint Code

        steps:
            - name: Clone Repository
              uses: actions/checkout@v2

            - name: Set up Python Environment
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 black
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run Linters
              uses: samuelmeuli/lint-action@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  auto_fix: true
                  commit_message: ":green_heart: 使用 ${linter} 格式化代码"
                  black: true
                  black_args: ""
                  flake8: true
                  flake8_args: "--max-line-length 90 --ignore W"
